This dataset is from https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease

Additional Information

We use 24 + class = 25 ( 11  numeric ,14  nominal)


1.Age(numerical)  	  	age in years

2.Blood Pressure(numerical)	       	bp in mm/Hg

3.Specific Gravity(nominal)	  	sg - (1.005,1.010,1.015,1.020,1.025)

4.Albumin(nominal)		al - (0,1,2,3,4,5)

5.Sugar(nominal)		su - (0,1,2,3,4,5)

6.Red Blood Cells(nominal)	rbc - (normal,abnormal)

7.Pus Cell (nominal)		pc - (normal,abnormal)
 	
8.Pus Cell clumps(nominal)		pcc - (present,notpresent)
 	
9.Bacteria(nominal)		ba  - (present,notpresent)

10.Blood Glucose Random(numerical)				bgr in mgs/dl

11.Blood Urea(numerical)			bu in mgs/dl

12.Serum Creatinine(numerical)			sc in mgs/dl

13.Sodium(numerical)		sod in mEq/L

14.Potassium(numerical)			pot in mEq/L

15.Hemoglobin(numerical)		hemo in gms

16.Packed  Cell Volume(numerical) 	

17.White Blood Cell Count(numerical)		wc in cells/cumm
 	
18.Red Blood Cell Count(numerical)			rc in millions/cmm

19.Hypertension(nominal)			htn - (yes,no)

20.Diabetes Mellitus(nominal)			dm - (yes,no)

21.Coronary Artery Disease(nominal)		cad - (yes,no)

22.Appetite(nominal)			appet - (good,poor)

23.Pedal Edema(nominal)		pe - (yes,no)	

24.Anemia(nominal)		ane - (yes,no)

25.Class (nominal)		class - (ckd,notckd)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('kidney_disease.csv')

In [3]:
df.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [4]:
# Rename the columns for better readability
df.columns = [
    'id','age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar',
    'red_blood_cells', 'pus_cell', 'pus_cell_clumps', 'bacteria',
    'blood_glucose_random', 'blood_urea', 'serum_creatinine', 'sodium',
    'potassium', 'hemoglobin', 'packed_cell_volume', 'white_blood_cell_count',
    'red_blood_cell_count', 'hypertension', 'diabetes_mellitus',
    'coronary_artery_disease', 'appetite', 'pedal_edema', 'anemia', 'class'
]

In [5]:
df.head()

,id,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       400 non-null    int64
 1   age                      391 non-null    float64
 2   blood_pressure           388 non-null    float64
 3   specific_gravity         353 non-null    float64
 4   albumin                  354 non-null    float64
 5   sugar                    351 non-null    float64
 6   red_blood_cells          248 non-null    object
 7   pus_cell                 335 non-null    object
 8   pus_cell_clumps          396 non-null    object
 9   bacteria                 396 non-null    object
 10  blood_glucose_random     356 non-null    float64
 11  blood_urea               381 non-null    float64
 12  serum_creatinine         383 non-null    float64
 13  sodium                   313 non-null    float64
 14  potassium                312 non-null    float64
 15  hemoglobin               348 non-null    float64
 16  packed_cell_volume       330 non-null    object
 17  white_blood_cell_count   295 non-null    object
 18  red_blood_cell_count     270 non-null    object
 19  hypertension             398 non-null    object
 20  diabetes_mellitus        398 non-null    object
 21  coronary_artery_disease  398 non-null    object
 22  appetite                 399 non-null    object
 23  pedal_edema              399 non-null    object
 24  anemia                   399 non-null    object
 25  class                    400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [7]:
# Calculate the proportion of CKD patients
ckd_proportion = sum(df['class'] == 'ckd')*100 / len(df)
print('Proportion of CKD patients:',sum(df['class'] == 'ckd') ,', ',ckd_proportion,'%')

# Calculate the proportion of non-CKD patients
non_ckd_proportion = sum(df['class'] != 'ckd')*100 / len(df)
print('Proportion of non-CKD patients:',sum(df['class'] != 'ckd'),', ',non_ckd_proportion,'%')

Proportion of CKD patients: 248 ,  62.0 %
Proportion of non-CKD patients: 152 ,  38.0 %

In [8]:
df.head()

,id,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [9]:
df.columns

Index(['id', 'age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar',
       'red_blood_cells', 'pus_cell', 'pus_cell_clumps', 'bacteria',
       'blood_glucose_random', 'blood_urea', 'serum_creatinine', 'sodium',
       'potassium', 'hemoglobin', 'packed_cell_volume',
       'white_blood_cell_count', 'red_blood_cell_count', 'hypertension',
       'diabetes_mellitus', 'coronary_artery_disease', 'appetite',
       'pedal_edema', 'anemia', 'class'],
      dtype='object')

In [10]:
# Convert numerical columns to numeric data type
numeric_cols = [
    'age', 'blood_pressure','specific_gravity', 'albumin','sugar', 'blood_glucose_random', 'blood_urea',
    'serum_creatinine', 'sodium', 'potassium', 'hemoglobin',
    'packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count'
]

In [12]:
df[numeric_cols].replace(['?', '\t?'], np.nan, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_25656\1218369241.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_cols].replace(['?', '\t?'], np.nan, inplace=True)

In [16]:
df[numeric_cols]

,age,blood_pressure,specific_gravity,albumin,sugar,blood_glucose_random,blood_urea,serum_creatinine,sodium,potassium,hemoglobin,packed_cell_volume,white_blood_cell_count,red_blood_cell_count
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2
1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1

In [ ]:
import matplotlib.pyplot as plt

#Find the distribution of features
#Create a histogram
df.hist(figsize=(20,10),color='limegreen')
# Display the plot
plt.show()

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df['class'].unique()

In [ ]:
cat = {'ckd': 'ckd', 'ckd\t': 'ckd', 'notckd': 'notckd'}

# Convert the categorical variable to numeric codes
df['class'] = df['class'].map(cat)

In [ ]:
df[numeric_cols].info()

In [ ]:
df[numeric_cols] = df[numeric_cols].astype('float64')
df[numeric_cols].info()

In [ ]:
df.columns

In [ ]:
df['id', 'specific_gravity', 'albumin', 'sugar',
       'red_blood_cells', 'pus_cell', 'pus_cell_clumps', 'bacteria',
       'blood_glucose_random', 'blood_urea', 'serum_creatinine', 'sodium',
       'potassium', 'hemoglobin', 'packed_cell_volume',
       'white_blood_cell_count', 'red_blood_cell_count', 'hypertension',
       'diabetes_mellitus', 'coronary_artery_disease', 'appetite',
       'pedal_edema', 'anemia', 'class']

In [ ]:
object_cols = [
    'age', 'blood_pressure', 'blood_glucose_random', 'blood_urea',
    'serum_creatinine', 'sodium', 'potassium', 'hemoglobin',
    'packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count'
]

In [ ]:
colTransformer = ColumnTransformer([
    ('num', StandardScaler(), num_features),
    ('cat', OneHotEncoder(), cat_features)
    ],
    remainder='passthrough'  # i.e., leave the rest of the columns untouched -- otherwise, they're dropped
    )

In [ ]:
class_ckd={'ckd': 1, 'notckd': 0}

In [ ]:
df['classification'] = df['class'].map(class_ckd)

In [ ]:
import seaborn as sns

sns.scatterplot(x='day', y='tip', data=tip)

In [ ]:
cat = {'ckd': 0, 'medium': 1, 'long': 2}

# Convert the categorical variable to numeric codes
fixation_period['Period_codes'] = fixation_period['Period'].map(cat)

In [ ]:
# Create a pairwise scatter plot matrix
sns.pairplot(df.dropna(), diag_kind='kde')
plt.show()

In [ ]:
# Calculate correlation matrix
correlation_matrix = df.corr()

# Create correlation heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()